<a href="/schools/new">Create school</a>

<h2>Old schools</h2>
<table>
    <?php foreach ($schools as $school): ?>
        <tr>
            <td>
                <?= $school['id'] ?>
            </td>
            <td>
                <a href="/schools/<?= $school['id'] ?>"><?= $school['name'] ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<h2>New schools</h2>

<?php foreach ($newSchools as $school): ?>
    <div>
        <?= htmlspecialchars($school['name']) ?>
    </div>
<?php endforeach ?>