<form action="/schools" method="post">
    <div>
        <label>
            Название *
            <input type="text" name="school[name]" value="<?= htmlspecialchars($schoolData['name'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Содержимое *
        </label>
        <textarea type="text" name="school[body]"> <?= htmlspecialchars($schoolData['body'] ?? '') ?> </textarea>
        <?php if (isset($errors['body'])): ?>
            <div><?= $errors['body'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Create">
</form>
